-- Seed Family and Friends 3 vocabulary into the vocabulary master table.
-- Generated 2026-09-17.
-- Idempotent: ON CONFLICT (word) DO UPDATE COALESCE preserving earliest grade/unit.

CREATE TABLE IF NOT EXISTS "data_migrations" (
  "id" text PRIMARY KEY,
  "applied_at" timestamp with time zone NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM "data_migrations" WHERE "id" = '2026-09-17-family-friends-3-vocab'
  ) THEN

    INSERT INTO vocabulary (
      word,
      part_of_speech,
      af_f_level,
      af_f_unit,
      is_function_word,
      is_scaffold,
      is_picturable,
      updated_at
    ) VALUES
      ('april', 'noun', 'grade3', 0, false, false, true, now()),
      ('august', 'noun', 'grade3', 0, false, false, true, now()),
      ('december', 'noun', 'grade3', 0, false, false, true, now()),
      ('fast', 'adjective', 'grade3', 0, false, false, true, now()),
      ('february', 'noun', 'grade3', 0, false, false, true, now()),
      ('january', 'noun', 'grade3', 0, false, false, true, now()),
      ('july', 'noun', 'grade3', 0, false, false, true, now()),
      ('june', 'noun', 'grade3', 0, false, false, true, now()),
      ('march', 'noun', 'grade3', 0, false, false, true, now()),
      ('may', 'verb', 'grade3', 0, true, false, true, now()),
      ('november', 'noun', 'grade3', 0, false, false, true, now()),
      ('october', 'noun', 'grade3', 0, false, false, true, now()),
      ('september', 'noun', 'grade3', 0, false, false, true, now()),
      ('australia', 'noun', 'grade3', 1, false, false, true, now()),
      ('brazil', 'noun', 'grade3', 1, false, false, true, now()),
      ('fall', 'verb', 'grade3', 1, false, false, true, now()),
      ('garden', 'noun', 'grade3', 1, false, false, true, now()),
      ('mexico', 'noun', 'grade3', 1, false, false, true, now()),
      ('season', 'noun', 'grade3', 1, false, false, true, now()),
      ('south korea', 'noun', 'grade3', 1, false, false, true, now()),
      ('spain', 'noun', 'grade3', 1, false, false, true, now()),
      ('spring', 'noun', 'grade3', 1, false, false, true, now()),
      ('summer', 'noun', 'grade3', 1, false, false, true, now()),
      ('thailand', 'noun', 'grade3', 1, false, false, true, now()),
      ('the u.s.a.', 'noun', 'grade3', 1, false, false, true, now()),
      ('vietnam', 'noun', 'grade3', 1, false, false, true, now()),
      ('winter', 'noun', 'grade3', 1, false, false, true, now()),
      ('shop', 'noun', 'grade3', 2, false, false, true, now()),
      ('camera', 'noun', 'grade3', 3, false, false, true, now()),
      ('comics', 'noun', 'grade3', 3, false, false, true, now()),
      ('dvd player', 'noun', 'grade3', 3, false, false, true, now()),
      ('mp3 player', 'noun', 'grade3', 3, false, false, true, now()),
      ('pins', 'noun', 'grade3', 3, false, false, true, now()),
      ('postcards', 'noun', 'grade3', 3, false, false, true, now()),
      ('posters', 'noun', 'grade3', 3, false, false, true, now()),
      ('shells', 'noun', 'grade3', 3, false, false, true, now()),
      ('stickers', 'noun', 'grade3', 3, false, false, true, now()),
      ('turn off', 'noun', 'grade3', 3, false, false, true, now()),
      ('turn on', 'noun', 'grade3', 3, false, false, true, now()),
      ('tv', 'noun', 'grade3', 3, false, false, true, now()),
      ('beautiful', 'adjective', 'grade3', 4, false, false, true, now()),
      ('clean', 'adjective', 'grade3', 4, false, false, true, now()),
      ('dangerous', 'adjective', 'grade3', 4, false, false, true, now()),
      ('dive', 'verb', 'grade3', 4, false, false, true, now()),
      ('kayak', 'verb', 'grade3', 4, false, false, true, now()),
      ('polluted', 'adjective', 'grade3', 4, false, false, true, now()),
      ('safe', 'adjective', 'grade3', 4, false, false, true, now()),
      ('sail', 'verb', 'grade3', 4, false, false, true, now()),
      ('snorkel', 'verb', 'grade3', 4, false, false, true, now()),
      ('surf', 'verb', 'grade3', 4, false, false, true, now()),
      ('ugly', 'adjective', 'grade3', 4, false, false, true, now()),
      ('waterski', 'verb', 'grade3', 4, false, false, true, now()),
      ('windsurf', 'verb', 'grade3', 4, false, false, true, now()),
      ('camel', 'noun', 'grade3', 5, false, false, true, now()),
      ('crocodile', 'noun', 'grade3', 5, false, false, true, now()),
      ('flamingo', 'noun', 'grade3', 5, false, false, true, now()),
      ('free', 'adjective', 'grade3', 5, false, false, true, now()),
      ('funny', 'adjective', 'grade3', 5, false, false, true, now()),
      ('kangaroo', 'noun', 'grade3', 5, false, false, true, now()),
      ('lizard', 'noun', 'grade3', 5, false, false, true, now()),
      ('penguin', 'noun', 'grade3', 5, false, false, true, now()),
      ('sorry', 'adjective', 'grade3', 5, false, false, true, now()),
      ('zebra', 'noun', 'grade3', 5, false, false, true, now()),
      ('catch the bus', 'noun', 'grade3', 6, false, false, true, now()),
      ('every day', 'noun', 'grade3', 6, false, false, true, now()),
      ('finally', 'noun', 'grade3', 6, false, false, true, now()),
      ('first', 'adverb', 'grade3', 6, false, false, false, now()),
      ('next', 'adverb', 'grade3', 6, false, false, false, now()),
      ('then', 'adverb', 'grade3', 6, false, false, false, now()),
      ('walk to school', 'noun', 'grade3', 6, false, false, true, now()),
      ('actor', 'noun', 'grade3', 7, false, false, true, now()),
      ('cafe', 'noun', 'grade3', 7, false, false, true, now()),
      ('concert', 'noun', 'grade3', 7, false, false, true, now()),
      ('library', 'noun', 'grade3', 7, false, false, true, now()),
      ('movie', 'noun', 'grade3', 7, false, false, true, now()),
      ('movie theater', 'noun', 'grade3', 7, false, false, true, now()),
      ('museum', 'noun', 'grade3', 7, false, false, true, now()),
      ('playground', 'noun', 'grade3', 7, false, false, true, now()),
      ('shopping mall', 'noun', 'grade3', 7, false, false, true, now()),
      ('singer', 'noun', 'grade3', 7, false, false, true, now()),
      ('sports center', 'noun', 'grade3', 7, false, false, true, now()),
      ('swimming pool', 'noun', 'grade3', 7, false, false, true, now()),
      ('theater', 'noun', 'grade3', 7, false, false, true, now()),
      ('butter', 'noun', 'grade3', 8, false, false, true, now()),
      ('cereal', 'noun', 'grade3', 8, false, false, true, now()),
      ('cheese', 'noun', 'grade3', 8, false, false, true, now()),
      ('cucumber', 'noun', 'grade3', 8, false, false, true, now()),
      ('lemon', 'noun', 'grade3', 8, false, false, true, now()),
      ('melon', 'noun', 'grade3', 8, false, false, true, now()),
      ('noodles', 'noun', 'grade3', 8, false, false, true, now()),
      ('onion', 'noun', 'grade3', 8, false, false, true, now()),
      ('peas', 'noun', 'grade3', 8, false, false, true, now()),
      ('pepper', 'noun', 'grade3', 8, false, false, true, now()),
      ('potato', 'noun', 'grade3', 8, false, false, true, now()),
      ('salt', 'noun', 'grade3', 8, false, false, true, now()),
      ('bridge', 'noun', 'grade3', 9, false, false, true, now()),
      ('building', 'noun', 'grade3', 9, false, false, true, now()),
      ('country', 'noun', 'grade3', 9, false, false, true, now()),
      ('deep', 'adjective', 'grade3', 9, false, false, true, now()),
      ('high', 'adjective', 'grade3', 9, false, false, true, now()),
      ('lake', 'noun', 'grade3', 9, false, false, true, now()),
      ('mountain', 'noun', 'grade3', 9, false, false, true, now()),
      ('old', 'adjective', 'grade3', 9, false, false, true, now()),
      ('river', 'noun', 'grade3', 9, false, false, true, now()),
      ('waterfall', 'noun', 'grade3', 9, false, false, true, now()),
      ('wide', 'adjective', 'grade3', 9, false, false, true, now()),
      ('catch', 'verb', 'grade3', 10, false, false, true, now()),
      ('chase', 'verb', 'grade3', 10, false, false, true, now()),
      ('cross', 'verb', 'grade3', 10, false, false, true, now()),
      ('flowers', 'noun', 'grade3', 10, false, false, true, now()),
      ('fountain', 'noun', 'grade3', 10, false, false, true, now()),
      ('garbage can', 'noun', 'grade3', 10, false, false, true, now()),
      ('grass', 'noun', 'grade3', 10, false, false, true, now()),
      ('laugh', 'verb', 'grade3', 10, false, false, true, now()),
      ('litter', 'noun', 'grade3', 10, false, false, true, now()),
      ('meet', 'verb', 'grade3', 10, false, false, true, now()),
      ('path', 'noun', 'grade3', 10, false, false, true, now()),
      ('shout', 'verb', 'grade3', 10, false, false, true, now()),
      ('trees', 'noun', 'grade3', 10, false, false, true, now()),
      ('along', 'preposition', 'grade3', 11, false, false, true, now()),
      ('between', 'preposition', 'grade3', 11, true, false, true, now()),
      ('bus', 'noun', 'grade3', 11, false, false, true, now()),
      ('ferry', 'noun', 'grade3', 11, false, false, true, now()),
      ('helicopter', 'noun', 'grade3', 11, false, false, true, now()),
      ('inside', 'preposition', 'grade3', 11, false, false, true, now()),
      ('motorcycle', 'noun', 'grade3', 11, false, false, true, now()),
      ('plane', 'noun', 'grade3', 11, false, false, true, now()),
      ('taxi', 'noun', 'grade3', 11, false, false, true, now()),
      ('through', 'preposition', 'grade3', 11, true, false, true, now()),
      ('trolley', 'noun', 'grade3', 11, false, false, true, now()),
      ('cheerful', 'adjective', 'grade3', 12, false, false, true, now()),
      ('friendly', 'adjective', 'grade3', 12, false, false, true, now()),
      ('generous', 'adjective', 'grade3', 12, false, false, true, now()),
      ('handsome', 'adjective', 'grade3', 12, false, false, true, now()),
      ('mean', 'adjective', 'grade3', 12, false, false, true, now()),
      ('pretty', 'adjective', 'grade3', 12, false, false, true, now()),
      ('relaxed', 'adjective', 'grade3', 12, false, false, true, now()),
      ('sad', 'adjective', 'grade3', 12, false, false, true, now()),
      ('shy', 'adjective', 'grade3', 12, false, false, true, now()),
      ('worried', 'adjective', 'grade3', 12, false, false, true, now()),
      ('young', 'adjective', 'grade3', 12, false, false, true, now()),
      ('difficult', 'adjective', 'grade3', 13, false, false, true, now()),
      ('easy', 'adjective', 'grade3', 13, false, false, true, now()),
      ('finish', 'verb', 'grade3', 13, false, false, true, now()),
      ('hard', 'adjective', 'grade3', 13, false, false, true, now()),
      ('hate', 'verb', 'grade3', 13, false, false, true, now()),
      ('heavy', 'adjective', 'grade3', 13, false, false, true, now()),
      ('light', 'adjective', 'grade3', 13, false, false, true, now()),
      ('live', 'verb', 'grade3', 13, false, false, true, now()),
      ('love', 'verb', 'grade3', 13, false, false, true, now()),
      ('soft', 'adjective', 'grade3', 13, false, false, true, now()),
      ('start', 'verb', 'grade3', 13, false, false, true, now()),
      ('use', 'verb', 'grade3', 13, false, false, true, now()),
      ('want', 'verb', 'grade3', 13, false, false, true, now()),
      ('apron', 'noun', 'grade3', 14, false, false, true, now()),
      ('backpack', 'noun', 'grade3', 14, false, false, true, now()),
      ('calculator', 'noun', 'grade3', 14, false, false, true, now()),
      ('dictionary', 'noun', 'grade3', 14, false, false, true, now()),
      ('flashlight', 'noun', 'grade3', 14, false, false, true, now()),
      ('frying pan', 'noun', 'grade3', 14, false, false, true, now()),
      ('matches', 'noun', 'grade3', 14, false, false, true, now()),
      ('p.e. clothes', 'noun', 'grade3', 14, false, false, true, now()),
      ('paintbrush', 'noun', 'grade3', 14, false, false, true, now()),
      ('rope', 'noun', 'grade3', 14, false, false, true, now()),
      ('sleeping bag', 'noun', 'grade3', 14, false, false, true, now()),
      ('tent', 'noun', 'grade3', 14, false, false, true, now()),
      ('hairbrush', 'noun', 'grade3', 15, false, false, true, now()),
      ('later', 'noun', 'grade3', 15, false, false, true, now()),
      ('next week', 'noun', 'grade3', 15, false, false, true, now()),
      ('shampoo', 'noun', 'grade3', 15, false, false, true, now()),
      ('soap', 'noun', 'grade3', 15, false, false, true, now()),
      ('soon', 'noun', 'grade3', 15, false, false, false, now()),
      ('suitcase', 'noun', 'grade3', 15, false, false, true, now()),
      ('this afternoon', 'noun', 'grade3', 15, false, false, true, now()),
      ('tomorrow', 'noun', 'grade3', 15, false, false, true, now()),
      ('tonight', 'noun', 'grade3', 15, false, false, true, now()),
      ('toothbrush', 'noun', 'grade3', 15, false, false, true, now()),
      ('toothpaste', 'noun', 'grade3', 15, false, false, true, now()),
      ('towel', 'noun', 'grade3', 15, false, false, true, now())
    ON CONFLICT (word) DO UPDATE SET
      part_of_speech = COALESCE(vocabulary.part_of_speech, EXCLUDED.part_of_speech),
      af_f_level = COALESCE(vocabulary.af_f_level, EXCLUDED.af_f_level),
      af_f_unit = COALESCE(vocabulary.af_f_unit, EXCLUDED.af_f_unit),
      is_function_word = vocabulary.is_function_word OR EXCLUDED.is_function_word,
      is_picturable = COALESCE(vocabulary.is_picturable, EXCLUDED.is_picturable),
      is_scaffold = false,
      updated_at = now();

    INSERT INTO "data_migrations" ("id") VALUES ('2026-09-17-family-friends-3-vocab');
  END IF;
END $$;

-- Confirmation
SELECT count(*) AS grade3_vocab_count FROM vocabulary WHERE af_f_level = 'grade3';
