import { readFile } from 'node:fs/promises';
import path from 'node:path';
import Anthropic from '@anthropic-ai/sdk';

export type QuestionType = 'fill_blank_mcq' | 'true_false';

export type GeneratedQuestion = {
  prompt: string;
  correctAnswer: string;
  distractors: string[];
  imagePrompt: string;
};

type UnitCurriculum = {
  unit: number;
  topic: string;
  vocabulary: Array<{ word: string; image?: string }>;
  numbers?: string[];
  prepositions?: string[];
  colors?: string[];
  grammar_patterns: Array<{ pattern: string; examples?: string[] }>;
  key_sentences?: string[];
};

// ---------- JSON loader ----------

async function loadUnitJson(unit: number): Promise<UnitCurriculum | null> {
  const jsonPath = path.join(process.cwd(), 'src', 'lib', 'curriculum', `unit-${unit}.json`);
  try {
    const contents = await readFile(jsonPath, 'utf-8');
    return JSON.parse(contents) as UnitCurriculum;
  } catch {
    return null;
  }
}

function formatCurriculumText(c: UnitCurriculum): string {
  const lines: string[] = [];
  lines.push(`UNIT ${c.unit} — ${c.topic}`);
  lines.push('');
  lines.push(`VOCABULARY (use these nouns only): ${c.vocabulary.map((v) => v.word).join(', ')}`);
  if (c.numbers?.length) {
    lines.push(`NUMBERS (use these only): ${c.numbers.join(', ')}`);
  }
  if (c.prepositions?.length) {
    lines.push(`PREPOSITIONS (use these only): ${c.prepositions.join(', ')}`);
  }
  if (c.colors?.length) {
    lines.push(`COLORS (use these only): ${c.colors.join(', ')}`);
  }
  lines.push('');
  lines.push('GRAMMAR PATTERNS (use these sentence shapes):');
  for (const gp of c.grammar_patterns) {
    lines.push(`• ${gp.pattern}`);
    if (gp.examples?.length) {
      const ex = gp.examples.slice(0, 3).map((e) => `"${e}"`).join(' / ');
      lines.push(`    e.g. ${ex}`);
    }
  }
  if (c.key_sentences?.length) {
    lines.push('');
    lines.push('STYLE REFERENCE (match the simplicity of these):');
    for (const s of c.key_sentences) {
      lines.push(`• ${s}`);
    }
  }
  return lines.join('\n');
}

// ---------- Prompts ----------

const MCQ_SYSTEM_PROMPT = `You create fill-in-the-blank multiple-choice questions for Grade 1 ESL students (age 6-7).

You will be given the curriculum specification for one unit as a structured text block. Treat it as the authoritative source for which vocabulary, grammar patterns, and sentence styles this student has studied.

STRICT RULES:
1. Every sentence must use ONLY words, numbers, prepositions, or grammar patterns listed in the provided specification. Never introduce content outside it.
2. Each question is a short sentence with exactly ONE blank written as "____" (four underscores).
3. Each question has exactly one correct answer and exactly three wrong distractors.
4. The correct answer must be UNAMBIGUOUSLY correct given the picture that accompanies the question (described below). The picture is what disambiguates between possible answers — for example, "There is ____ pillow on the bed." with a picture showing one pillow → "a"; with two pillows → "two".
5. Distractors must be real words from the same category as the correct answer and must appear in the provided specification (if the blank is a preposition, distractors are other prepositions; if it's a noun, other nouns from this unit's vocabulary; etc.).
6. Mix blank types: some grammar-focused (e.g. "It's ___ bag." → "my"), some vocabulary-focused (e.g. "It's a ___." → "pen"), some preposition-focused if the unit teaches prepositions, some quantity-focused if numbers are taught.
7. Keep sentences very short (3-7 words), matching the style of the unit's key sentences.
8. Vary the sentences — no two prompts should be identical.

For each question also produce an "imagePrompt": a short, concrete description (1 sentence, ~10-20 words) of a clipart-style scene that shows the answer. The image will be generated by an AI image model and shown above the sentence to the student. Describe quantities, positions, and objects literally so the picture cannot be misread. Examples:
- Question "There is a pillow ____ the bed." (answer "on") → imagePrompt: "A single pillow resting on top of a neatly made bed."
- Question "There are ____ rugs on the floor." (answer "two") → imagePrompt: "Two rectangular rugs lying side by side on a wooden floor."

Return the result as JSON matching the provided schema.`;

const TRUE_FALSE_SYSTEM_PROMPT = `You create true/false picture questions for Grade 1 ESL students (age 6-7).

You will be given the curriculum specification for one unit as a structured text block. Treat it as the authoritative source for which vocabulary, grammar patterns, and sentence styles this student has studied.

STRICT RULES:
1. Every statement must use ONLY words, numbers, prepositions, or grammar patterns listed in the provided specification. Never introduce content outside it.
2. Each question is a SHORT, COMPLETE statement (3-7 words) — no blanks, no underscores. The student decides if the statement is TRUE or FALSE based on the picture.
3. "correctAnswer" must be EXACTLY the lowercase string "true" or "false".
4. Mix true and false roughly evenly across the batch.
5. The picture is what makes the answer unambiguous. The statement and the picture together must have only one correct verdict.
6. Vary the sentences — no two prompts should be identical.
7. Match the simplicity of the unit's key sentences.

For each question also produce an "imagePrompt": a short, concrete description (1 sentence, ~10-20 words) of a clipart-style scene the student looks at. Describe quantities, positions, and objects literally so the picture cannot be misread. Examples:
- Statement "There are three dolls on the rug." (answer "true") → imagePrompt: "Three small dolls sitting in a row on a rectangular rug on a wooden floor."
- Statement "There is a pillow under the bed." (answer "false") → imagePrompt: "A single pillow resting on top of a neatly made bed, nothing under the bed."

Return the result as JSON matching the provided schema.`;

// ---------- JSON schema ----------

const MCQ_QUESTION_SCHEMA = {
  type: 'object',
  properties: {
    questions: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          prompt: { type: 'string' },
          correctAnswer: { type: 'string' },
          distractors: {
            type: 'array',
            items: { type: 'string' },
          },
          imagePrompt: { type: 'string' },
        },
        required: ['prompt', 'correctAnswer', 'distractors', 'imagePrompt'],
        additionalProperties: false,
      },
    },
  },
  required: ['questions'],
  additionalProperties: false,
} as const;

const TRUE_FALSE_QUESTION_SCHEMA = {
  type: 'object',
  properties: {
    questions: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          prompt: { type: 'string' },
          correctAnswer: { type: 'string', enum: ['true', 'false'] },
          imagePrompt: { type: 'string' },
        },
        required: ['prompt', 'correctAnswer', 'imagePrompt'],
        additionalProperties: false,
      },
    },
  },
  required: ['questions'],
  additionalProperties: false,
} as const;

function validateMcqShape(raw: unknown): GeneratedQuestion[] {
  if (typeof raw !== 'object' || raw === null) throw new Error('Response is not an object');
  const questions = (raw as { questions?: unknown }).questions;
  if (!Array.isArray(questions)) throw new Error('Missing questions array');

  return questions.filter((q): q is GeneratedQuestion => {
    if (typeof q !== 'object' || q === null) return false;
    const obj = q as Record<string, unknown>;
    return (
      typeof obj.prompt === 'string' &&
      obj.prompt.includes('____') &&
      typeof obj.correctAnswer === 'string' &&
      obj.correctAnswer.length > 0 &&
      Array.isArray(obj.distractors) &&
      obj.distractors.length === 3 &&
      obj.distractors.every((d) => typeof d === 'string' && d.length > 0) &&
      typeof obj.imagePrompt === 'string' &&
      obj.imagePrompt.length > 0
    );
  });
}

function validateTrueFalseShape(raw: unknown): GeneratedQuestion[] {
  if (typeof raw !== 'object' || raw === null) throw new Error('Response is not an object');
  const questions = (raw as { questions?: unknown }).questions;
  if (!Array.isArray(questions)) throw new Error('Missing questions array');

  return questions
    .filter((q): q is { prompt: string; correctAnswer: string; imagePrompt: string } => {
      if (typeof q !== 'object' || q === null) return false;
      const obj = q as Record<string, unknown>;
      const answer = typeof obj.correctAnswer === 'string' ? obj.correctAnswer.toLowerCase() : '';
      return (
        typeof obj.prompt === 'string' &&
        obj.prompt.length > 0 &&
        !obj.prompt.includes('____') &&
        (answer === 'true' || answer === 'false') &&
        typeof obj.imagePrompt === 'string' &&
        obj.imagePrompt.length > 0
      );
    })
    .map((q) => {
      const answer = q.correctAnswer.toLowerCase();
      return {
        prompt: q.prompt,
        correctAnswer: answer,
        distractors: [answer === 'true' ? 'false' : 'true'],
        imagePrompt: q.imagePrompt,
      };
    });
}

// ---------- Main ----------

export async function generateQuestions(params: {
  unit: number;
  count: number;
  questionType?: QuestionType;
}): Promise<GeneratedQuestion[]> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error('ANTHROPIC_API_KEY is not configured');

  const questionType: QuestionType = params.questionType ?? 'fill_blank_mcq';
  const isTrueFalse = questionType === 'true_false';
  const systemPrompt = isTrueFalse ? TRUE_FALSE_SYSTEM_PROMPT : MCQ_SYSTEM_PROMPT;
  const schema = isTrueFalse ? TRUE_FALSE_QUESTION_SCHEMA : MCQ_QUESTION_SCHEMA;
  const validate = isTrueFalse ? validateTrueFalseShape : validateMcqShape;
  const userInstruction = isTrueFalse
    ? `Generate ${params.count} true/false picture statements at Grade 1 ESL difficulty based on the Unit ${params.unit} specification above. Mix true and false roughly evenly.`
    : `Generate ${params.count} fill-in-the-blank multiple-choice questions at Grade 1 ESL difficulty based on the Unit ${params.unit} specification above.`;

  const client = new Anthropic({ apiKey });

  const curriculum = await loadUnitJson(params.unit);
  if (!curriculum) {
    throw new Error(`No curated curriculum for Unit ${params.unit} — add src/lib/curriculum/unit-${params.unit}.json before generating questions.`);
  }

  const userContent: Anthropic.ContentBlockParam[] = [
    {
      type: 'text',
      text: formatCurriculumText(curriculum),
      cache_control: { type: 'ephemeral' },
    },
  ];

  userContent.push({
    type: 'text',
    text: userInstruction,
  });

  const response = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 2000,
    thinking: { type: 'disabled' },
    output_config: {
      effort: 'medium',
      format: { type: 'json_schema', schema },
    },
    system: [
      {
        type: 'text',
        text: systemPrompt,
        cache_control: { type: 'ephemeral' },
      },
    ],
    messages: [{ role: 'user', content: userContent }],
  });

  const text = response.content
    .filter((b): b is Anthropic.TextBlock => b.type === 'text')
    .map((b) => b.text)
    .join('')
    .trim();

  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    throw new Error('Model did not return valid JSON');
  }

  return validate(parsed);
}
