import { readFile } from 'node:fs/promises';
import path from 'node:path';
import Anthropic from '@anthropic-ai/sdk';

export type GeneratedQuestion = {
  prompt: string;
  correctAnswer: string;
  distractors: string[];
  imagePrompt: string;
};

type UnitCurriculum = {
  unit: number;
  topic: string;
  vocabulary: Array<{ word: string; image?: string }>;
  numbers?: string[];
  prepositions?: string[];
  colors?: string[];
  grammar_patterns: Array<{ pattern: string; examples?: string[] }>;
  key_sentences?: string[];
};

// ---------- JSON loader ----------

async function loadUnitJson(unit: number): Promise<UnitCurriculum | null> {
  const jsonPath = path.join(process.cwd(), 'src', 'lib', 'curriculum', `unit-${unit}.json`);
  try {
    const contents = await readFile(jsonPath, 'utf-8');
    return JSON.parse(contents) as UnitCurriculum;
  } catch {
    return null;
  }
}

function formatCurriculumText(c: UnitCurriculum): string {
  const lines: string[] = [];
  lines.push(`UNIT ${c.unit} — ${c.topic}`);
  lines.push('');
  lines.push(`VOCABULARY (use these nouns only): ${c.vocabulary.map((v) => v.word).join(', ')}`);
  if (c.numbers?.length) {
    lines.push(`NUMBERS (use these only): ${c.numbers.join(', ')}`);
  }
  if (c.prepositions?.length) {
    lines.push(`PREPOSITIONS (use these only): ${c.prepositions.join(', ')}`);
  }
  if (c.colors?.length) {
    lines.push(`COLORS (use these only): ${c.colors.join(', ')}`);
  }
  lines.push('');
  lines.push('GRAMMAR PATTERNS (use these sentence shapes):');
  for (const gp of c.grammar_patterns) {
    lines.push(`• ${gp.pattern}`);
    if (gp.examples?.length) {
      const ex = gp.examples.slice(0, 3).map((e) => `"${e}"`).join(' / ');
      lines.push(`    e.g. ${ex}`);
    }
  }
  if (c.key_sentences?.length) {
    lines.push('');
    lines.push('STYLE REFERENCE (match the simplicity of these):');
    for (const s of c.key_sentences) {
      lines.push(`• ${s}`);
    }
  }
  return lines.join('\n');
}

// ---------- Prompts ----------

const SYSTEM_PROMPT = `You create fill-in-the-blank multiple-choice questions for Grade 1 ESL students (age 6-7).

You will be given the curriculum specification for one unit as a structured text block. Treat it as the authoritative source for which vocabulary, grammar patterns, and sentence styles this student has studied.

STRICT RULES:
1. Every sentence must use ONLY words, numbers, prepositions, or grammar patterns listed in the provided specification. Never introduce content outside it.
2. Each question is a short sentence with exactly ONE blank written as "____" (four underscores).
3. Each question has exactly one correct answer and exactly three wrong distractors.
4. The correct answer must be UNAMBIGUOUSLY correct given the picture that accompanies the question (described below). The picture is what disambiguates between possible answers — for example, "There is ____ pillow on the bed." with a picture showing one pillow → "a"; with two pillows → "two".
5. Distractors must be real words from the same category as the correct answer and must appear in the provided specification (if the blank is a preposition, distractors are other prepositions; if it's a noun, other nouns from this unit's vocabulary; etc.).
6. Mix blank types: some grammar-focused (e.g. "It's ___ bag." → "my"), some vocabulary-focused (e.g. "It's a ___." → "pen"), some preposition-focused if the unit teaches prepositions, some quantity-focused if numbers are taught.
7. Keep sentences very short (3-7 words), matching the style of the unit's key sentences.
8. Vary the sentences — no two prompts should be identical.

For each question also produce an "imagePrompt": a short, concrete description (1 sentence, ~10-20 words) of a clipart-style scene that shows the answer. The image will be generated by an AI image model and shown above the sentence to the student. Describe quantities, positions, and objects literally so the picture cannot be misread. Examples:
- Question "There is a pillow ____ the bed." (answer "on") → imagePrompt: "A single pillow resting on top of a neatly made bed."
- Question "There are ____ rugs on the floor." (answer "two") → imagePrompt: "Two rectangular rugs lying side by side on a wooden floor."

Return the result as JSON matching the provided schema.`;

// ---------- JSON schema ----------

const QUESTION_SCHEMA = {
  type: 'object',
  properties: {
    questions: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          prompt: { type: 'string' },
          correctAnswer: { type: 'string' },
          distractors: {
            type: 'array',
            items: { type: 'string' },
          },
          imagePrompt: { type: 'string' },
        },
        required: ['prompt', 'correctAnswer', 'distractors', 'imagePrompt'],
        additionalProperties: false,
      },
    },
  },
  required: ['questions'],
  additionalProperties: false,
} as const;

function validateShape(raw: unknown): GeneratedQuestion[] {
  if (typeof raw !== 'object' || raw === null) throw new Error('Response is not an object');
  const questions = (raw as { questions?: unknown }).questions;
  if (!Array.isArray(questions)) throw new Error('Missing questions array');

  return questions.filter((q): q is GeneratedQuestion => {
    if (typeof q !== 'object' || q === null) return false;
    const obj = q as Record<string, unknown>;
    return (
      typeof obj.prompt === 'string' &&
      obj.prompt.includes('____') &&
      typeof obj.correctAnswer === 'string' &&
      obj.correctAnswer.length > 0 &&
      Array.isArray(obj.distractors) &&
      obj.distractors.length === 3 &&
      obj.distractors.every((d) => typeof d === 'string' && d.length > 0) &&
      typeof obj.imagePrompt === 'string' &&
      obj.imagePrompt.length > 0
    );
  });
}

// ---------- Main ----------

export async function generateQuestions(params: {
  unit: number;
  count: number;
}): Promise<GeneratedQuestion[]> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error('ANTHROPIC_API_KEY is not configured');

  const client = new Anthropic({ apiKey });

  const curriculum = await loadUnitJson(params.unit);
  if (!curriculum) {
    throw new Error(`No curated curriculum for Unit ${params.unit} — add src/lib/curriculum/unit-${params.unit}.json before generating questions.`);
  }

  const userContent: Anthropic.ContentBlockParam[] = [
    {
      type: 'text',
      text: formatCurriculumText(curriculum),
      cache_control: { type: 'ephemeral' },
    },
  ];

  userContent.push({
    type: 'text',
    text: `Generate ${params.count} fill-in-the-blank multiple-choice questions at Grade 1 ESL difficulty based on the Unit ${params.unit} specification above.`,
  });

  const response = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 2000,
    thinking: { type: 'disabled' },
    output_config: {
      effort: 'medium',
      format: { type: 'json_schema', schema: QUESTION_SCHEMA },
    },
    system: [
      {
        type: 'text',
        text: SYSTEM_PROMPT,
        cache_control: { type: 'ephemeral' },
      },
    ],
    messages: [{ role: 'user', content: userContent }],
  });

  const text = response.content
    .filter((b): b is Anthropic.TextBlock => b.type === 'text')
    .map((b) => b.text)
    .join('')
    .trim();

  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    throw new Error('Model did not return valid JSON');
  }

  return validateShape(parsed);
}
